#!/bin/bash

if [[ -z $VIRTUAL_ENV ]]; then
    source .env/bin/activate
fi

if [[ $1 =~ ^(server)$ ]]; then
    flask --debug --app main.py run --port=7000

elif [[ $1 =~ ^(dev)$ ]]; then
    npm start

elif [[ $1 =~ ^(build)$ ]]; then
    if [[ $2 =~ ^(watch|w)$ ]]; then
        npm run build:watch
    else
        npm run build
    fi

elif [[ $1 =~ ^(log)$ ]]; then
    cat *.log

elif [[ $1 =~ ^(tag)$ ]]; then
    if [[ -z $2 ]]; then
        exit
    else
        git push
        git tag -a "v$2" -m "release $2"
        git push origin "v$2"
    fi

elif [[ $1 =~ ^(delete all tags)$ ]]; then
    # git tag | grep <pattern> | xargs -n 1 -i% git push origin :refs/tags/%
    git tag | xargs -n 1 -i% sh -c 'git push origin :% && git tag -d %'

fi
