name: Test the Locales 🐣

on:
  pull_request:
    paths:
      - 'locale/*.json'

jobs:
  verify:
    name: Verify the Locales by schema
    runs-on: ubuntu-latest
    steps:
      - run: echo GGEZ
      # - uses: actions/checkout@v3
      # - name: Validate Locales
      #   uses: FalsePattern/json-schema-validator@master
      #   with:
      #     json_schema: ./locale/schema.json
      #     json_path_pattern: ^(\.\/locale\/)(?!schema).+\.json$
